---
title: "Assignment 6"
author: "Oyvind Nordgard"
date: "25 november 2018"
output: html_document
---

```{r setup, include=FALSE}
getwd()
setwd("D:/Github/Assignment6")
library(readr)
library(tidyverse)
library(latticeExtra)
library(skimr)
library(plyr)

```

#TASK 1

```{r}
DS = tribble(
  ~fk_account_code, ~Ansvar, ~fk_function_code, ~fk_project_code, ~amount,
  101030,40220,"Det",3432,1493.00,
  101030,40220,"Met",3586,2827.00,
  101030,40320,"Det",3456,49440.00,
  101030,40330,"Sal",NA,870716.00,
  101030,40350,"Met",NA,559928.00,
  101030,40360,"Sal",NA,125534.00,
  101030,40280,"Pol",NA,251611.00)
```

 *Removing the "fk_project_code" variable from DS*
```{r}
glimpse(DS)
DS["fk_project_code"]<- NULL
```
 
 * Sum the "amount" by the 3 first digits of Ansvar; 402, 403, ....
```{r}
DS$Ansvar<-sub("^(\\d{3}).*$", "\\1", DS$Ansvar)
DS$Ansvar<-as.numeric(DS$Ansvar)
DS$amount<-as.numeric(DS$amount)
rowSums(DS[,c(2,4)])
```
 
 *Make new "labels" for "fk_function_code", where:*
 *"Det" and "Sal" is "Supplies", "Met" is "Inventories", "Pol" is "Other expenses"*
```{r}
DS$fk_function_code<-recode(DS$fk_function_code,
                            "Met"="Inventories",
                            "Pol" = "Other expenses", 
                            "Det" = "Supplies",
                            "Sal" = "Supplies" )
glimpse(DS)
```

#Task 2

```{r}
df <- data.frame(Product=gl(3,10,labels=c("A","B", "C")), 
                 Year=factor(rep(2002:2011,3)), 
                 Sales=1:30)
glimpse(df)
```

* Calculating the share of sales per product per year
```{r}
ratio<-function(x) x/sum(x)
df_sale_ratio<-ddply(df, "Year", transform, Share=ratio(Sales))
```
 
 * Plot of the sales and shares per year per company.
```{r}
library(latticeExtra)
asTheEconomist(
  xyplot(Sales + Share ~ Year, groups=Product, 
         data=df_sale_ratio, t="b", 
         scales=list(relation="free",x=list(rot=45)), 
         auto.key=list(space="top", column=3),
         main="Company progress")
)
```